-- MySQL Script generated by MySQL Workbench
-- Sat Mar  4 16:25:08 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- -----------------------------------------------------
-- Schema editorialdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `editorialdb`;
-- -----------------------------------------------------
-- Table `editorialdb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `editorialdb`.`user` (
  `id` BIGINT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(75) NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`));
-- -----------------------------------------------------
-- Table `editorialdb`.`article_correct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `editorialdb`.`article_correct` (
  `id_correct` BIGINT NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `content` LONGTEXT NOT NULL,
  `date_of_correction` DATETIME NULL,
  `is_corrected` TINYINT(1) NOT NULL,
  `journalist_id_c` BIGINT NOT NULL,
  `corrector_id_c` BIGINT NULL,
  PRIMARY KEY (`id_correct`),
  INDEX `article_fk_idx` (`corrector_id_c` ASC),
  CONSTRAINT `article_fk`
    FOREIGN KEY (`corrector_id_c`)
    REFERENCES `editorialdb`.`user` (`id`));
-- -----------------------------------------------------
-- Table `editorialdb`.`article_draft`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `editorialdb`.`article_draft` (
  `id_draft` BIGINT NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `content` LONGTEXT NOT NULL,
  `date_of_completion` DATETIME NULL,
  `journalist_id_d` BIGINT NOT NULL,
  PRIMARY KEY (`id_draft`),
  INDEX `draft_fk_idx` (`journalist_id_d` ASC),
  CONSTRAINT `draft_fk`
    FOREIGN KEY (`journalist_id_d`)
    REFERENCES `editorialdb`.`user` (`id`));
-- -----------------------------------------------------
-- Table `editorialdb`.`article_proposal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `editorialdb`.`article_proposal` (
  `id_proposal` BIGINT NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `keywords` VARCHAR(200) NOT NULL,
  `is_accepted` TINYINT(1) NOT NULL,
  `journalist_id_p` BIGINT NOT NULL,
  PRIMARY KEY (`id_proposal`),
  INDEX `redactor_id_fk_idx` (`journalist_id_p` ASC),
  CONSTRAINT `redactor_id_fk`
    FOREIGN KEY (`journalist_id_p`)
    REFERENCES `editorialdb`.`user` (`id`));
-- -----------------------------------------------------
-- Table `editorialdb`.`authority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `editorialdb`.`authority` (
  `user_id_a` BIGINT NOT NULL,
  `authority` VARCHAR(45) NOT NULL,
  INDEX `authority_fk` (`user_id_a` ASC),
  CONSTRAINT `authority_fk`
    FOREIGN KEY (`user_id_a`)
    REFERENCES `editorialdb`.`user` (`id`));
-- -----------------------------------------------------
-- Table `editorialdb`.`user_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `editorialdb`.`user_detail` (
  `user_id_d` BIGINT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `supplier` VARCHAR(30) NOT NULL,
  INDEX `user_id_fk_idx` (`user_id_d` ASC),
  CONSTRAINT `user_id_fk`
    FOREIGN KEY (`user_id_d`)
    REFERENCES `editorialdb`.`user` (`id`));