-- MySQL Script generated by MySQL Workbench
-- Sat Mar  4 16:28:10 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- -----------------------------------------------------
-- Schema userdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `userdb`;
-- -----------------------------------------------------
-- Table `userdb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `userdb`.`user` (
  `id` BIGINT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(75) NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`));
-- -----------------------------------------------------
-- Table `userdb`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `userdb`.`article` (
  `id_article` BIGINT NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `journalist_id_a` BIGINT NOT NULL,
  `article_content` LONGTEXT NOT NULL,
  `category` VARCHAR(200) NOT NULL,
  `date_of_submission` DATETIME NOT NULL,
  PRIMARY KEY (`id_article`),
  INDEX `owner_id_fk_idx` (`journalist_id_a` ASC),
  CONSTRAINT `owner_id_fk`
    FOREIGN KEY (`journalist_id_a`)
    REFERENCES `userdb`.`user` (`id`));
-- -----------------------------------------------------
-- Table `userdb`.`authority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `userdb`.`authority` (
  `user_id_a` BIGINT NOT NULL,
  `authority` VARCHAR(45) NOT NULL,
  INDEX `role_id_fk_idx` (`user_id_a` ASC),
  CONSTRAINT `role_id_fk`
    FOREIGN KEY (`user_id_a`)
    REFERENCES `userdb`.`user` (`id`));
-- -----------------------------------------------------
-- Table `userdb`.`endorsement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `userdb`.`endorsement` (
  `fk_article` BIGINT NOT NULL,
  `fk_user` BIGINT NOT NULL,
  `endorsement_value` TINYINT(1) NOT NULL,
  INDEX `fk_article_key_idx` (`fk_article` ASC),
  INDEX `fk_user_owner_key_idx` (`fk_user` ASC),
  CONSTRAINT `fk_article_key`
    FOREIGN KEY (`fk_article`)
    REFERENCES `userdb`.`article` (`id_article`),
  CONSTRAINT `fk_user_owner_key`
    FOREIGN KEY (`fk_user`)
    REFERENCES `userdb`.`user` (`id`));
-- -----------------------------------------------------
-- Table `userdb`.`user_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `userdb`.`user_detail` (
  `user_id_d` BIGINT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `supplier` VARCHAR(30) NOT NULL,
  INDEX `user_id_fk_idx` (`user_id_d` ASC),
  CONSTRAINT `user_id_fk`
    FOREIGN KEY (`user_id_d`)
    REFERENCES `userdb`.`user` (`id`));